---
- name: create aws instance
  hosts: localhost
  user: serveradmin

  tasks:
    - name: create key pair for instances
      ec2_key:
          name: ansinstances
          region: us-east-1
      register: ec2_key_result

    - name: Save private key
      copy: content="{{ ec2_key_result.key.private_key }}" dest=".ssh/id_rsa" mode=0400
      when: ec2_key_result.changed

    - name: start specific number of multiple instances
      amazon.aws.ec2_instance:
          key_name: "ansinstances"
          instance_type: t2.micro
          image_id: ami-08c40ec9ead489470
          count: 2
          region: us-east-1
          network:
            assign_public_ip: yes
            security_group: default
            vpc_subnet_id: subnet-0c3b88d08d2ebd335
          state: present

    - name: add host builder
      add_host:
        name: "{{ ec2.instances[0].public.ip }}"
        groups: mvn
      with_items: "{{ ec2.istances }}"

    - name: add host prod
      add_host:
        name: "{{ ec2.instances[1].public.ip }}"
        groups: tom
      with_items: "{{ ec2.istances }}"

- name: Repo and cache servers update
  hosts: all
  become: yes 

  tasks:
  - name: repo and cahe update
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600
      
- name: create app file ready to deploy
  hosts: mvn
  become: yes

  tasks:  
  - name: ensure git, jdk, maven packages is present
    apt:
      name: "{{item}}"
      state: present
    with_items:
      - git
      - default-jdk
      - maven  
  
  - name: make directory for git pull and packages
    file:
      path: /home/app
      state: directory
  - name: clone code from git
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /home/app  
  - name: make war file
    shell:
      chdir: /home/app
      cmd: mvn package

- name: install tomcat
  hosts: tom
  become: yes
    
  tasks: 
  - name: ensure tomcat is present
    apt:
      name: tomcat9
      state: present

- name: deploy app
  hosts: mvn
  become: yes

  tasks:
  - name: copy to local
    synchronize:
      src: /home/app/target/hello-1.0.war
      dest: /tmp/hello-1.0.war
      mode: pull

- name: deploy app
  hosts: tom
  become: yes

  tasks:
  - name: copy to tom
    synchronize:
      src: /tmp/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/hello-1.0.war